package:
  name: nexus
  version: "4.4.3"

source:
  git_rev: v4.4.3
  git_url: https://github.com/nexusformat/code.git

requirements:
  build:
    - libtool
    - automake
    - cmake
    - hdf5 1.8.18
    - hdf4

  run:
    - hdf5 1.8.18
    - hdf4

test:
  imports:

about:
  home: 
  license:
  license_file:
