{% set version = "4.0.20190614.2051" %}
{% set git_rev = "4e4ffc7e331d610b593d84f92b3206f275606a5b" %}

package:
  name: mantid-workbench
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - cmake
  host:
    - python
    - boost     {{ boost }}
    - eigen     {{ eigen }}
    - hdf4      {{ hdf4 }}
    - hdf5      {{ hdf5 }}
    - muparser  {{ muparser }}
    - gsl       {{ gsl }}
    - openblas  {{ openblas }}
    - blas      {{ blas }}
    - numpy     {{ numpy }} 
    - poco      {{ poco }}
    - nexus     {{ nexus }}
    - jsoncpp   {{ jsoncpp }}
    - tbb       {{ tbb }}
    - librdkafka  {{ librdkafka }}
    - qt        {{ qt }}
    - pyqt      {{ pyqt }}
    - qtpy      {{ qtpy }}
    - qtconsole {{ qtconsole }}
    - qscintilla2 {{ qscintilla2 }}
    - qtawesome {{ qtawesome }}
    - sphinx    {{ sphinx }}
    - sphinx_bootstrap_theme {{ sphinx_bootstrap_theme }}
    - h5py
    - mpi4py
    - openssl
    - python-dateutil
    - readline
    - scipy

  run:
    - python
    - boost
    - eigen
    - hdf4
    - hdf5
    - icu
    - muparser 2.2.5 0
    - gsl
    - openblas
    - blas
    - numpy
    - poco
    - nexus
    - jsoncpp
    - tbb
    - librdkafka
    - readline
    - openssl
    - qt
    - pyqt
    - qtpy
    - qtconsole
    - qscintilla2
    - qtawesome
    - psutil
    - requests
    - python-dateutil
    - h5py
    - mpi4py
    - scipy
    - scikit-image
    - pyyaml
    - pycifrw
    - matplotlib
    - six
    - cmake
    - psutil
    - requests

build:
  script_env:
    - CC
    - CXX
    - OPENGL_gl_LIBRARY
    - OPENGL_glu_LIBRARY
    - OPENGL_INCLUDES
  string:

about:
  home:
  license:
  license_file:
