python:
  - 2.7.14
#  - 3.6
boost:
#  - 1.61
  - 1.66
eigen:
  - 3.3.3
hdf4:
  - 4.2.13
hdf5:
  - 1.8.18
muparser:
  - 2.2.5
gsl:
#  - 1.16
  - 2.4
openblas:
  - 0.2.20
blas:
  - 1.1 openblas
numpy:
#  - 1.13
  - 1.14
poco:
  - 1.7.3
nexus:
  - 4.4.3
jsoncpp:
  - 0.10.6
tbb:
  - 2018_20170919
librdkafka:
  - 0.11

zip_keys:
  - boost
  - gsl
  - numpy

pin_run_as_build:
  boost:
    max_pin: x.x
  eigen:
    max_pin: x.x
  hdf4:
    max_pin: x.x
  hdf5:
    max_pin: x.x
  muparser:
    max_pin: x.x
  gsl:
    max_pin: x.x
  openblas:
    max_pin: x.x
  blas:
    max_pin: x.x
  numpy:
    max_pin: x.x
  poco:
    max_pin: x.x
  nexus:
    max_pin: x.x
  jsoncpp:
    max_pin: x.x
  tbb:
    max_pin: x.x
  librdkafka:
    max_pin: x.x
