{% set version = "3.9.20170218.1707" %}
{% set git_rev = "66765dc3f05d4ad5c5d0d1b03be9c0f38b7c5400" %}

package:
  name: mantid-framework
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    - python
    - cmake
    - boost 1.61.*
    - hdf4
    - hdf5 1.8.15*
    - h5py
    - muparser
    - gsl
    - mpi4py
    - scipy
    - dateutil
    - readline
    - poco
    - nexus
    - openssl
    - jsoncpp
    - tbb

  run:
    - python
    - cmake
    - boost 1.61.*
    - hdf4
    - hdf5 1.8.15*
    - h5py
    - muparser
    - gsl
    - mpi4py
    - scipy
    - dateutil
    - readline
    - poco
    - nexus
    - openssl
    - jsoncpp
    - tbb

build:
  script_env:
    - OPENGL_gl_LIBRARY
    - OPENGL_glu_LIBRARY

about:
  home:
  license:
  license_file:
