{% set version = "3.10.20170731.2050" %}
{% set git_rev = "9c56b890c5776f41f151b5785df71fc7760a7c6c" %}

package:
  name: mantid-framework
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    - python
    - cmake
    - boost 1.61.*
    - hdf4
    - hdf5 1.8.18
    - h5py
    - muparser
    - gsl 1.16
    - mpi4py
    - openblas
    - numpy x.x
    - scipy
    - python-dateutil
    - readline
    - poco
    - nexus
    - openssl
    - jsoncpp
    - tbb

  run:
    - python
    - cmake
    - pyyaml
    - boost 1.61.*
    - hdf4
    - hdf5 1.8.18
    - h5py
    - muparser
    - gsl 1.16
    - mpi4py
    - openblas
    - numpy x.x
    - scipy
    - python-dateutil
    - readline
    - poco
    - nexus
    - openssl
    - jsoncpp
    - tbb

build:
  script_env:
    - CC
    - CXX
    - OPENGL_gl_LIBRARY
    - OPENGL_glu_LIBRARY

about:
  home:
  license:
  license_file:
