{% set version = "3.7.20160812" %}
{% set git_rev = "master" %}

package:
  name: mantid-framework
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    - python
    - cmake
    - boost
    - hdf4
    - hdf5 1.8.15*
    - h5py
    - muparser
    - gsl
    - mpi4py
    - scipy
    - dateutil
    - readline
    - poco
    - nexus
    - openssl
    - jsoncpp

  run:
    - python
    - cmake
    - boost
    - hdf4
    - hdf5 1.8.15*
    - h5py
    - muparser
    - gsl
    - mpi4py
    - scipy
    - dateutil
    - readline
    - poco
    - nexus
    - openssl
    - jsoncpp

test:
  imports:


about:
  home:
  license:
  license_file:
