{% set version = "3.11.20171215.1630" %}
{% set git_rev = "0eec908a66739a7fb3dc2eb2466c8355dd05cf7f" %}

package:
  name: mantid-framework
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    - python
    - cmake
    - boost 1.61.*
    - hdf4
    - hdf5 1.8.18
    - h5py
    - muparser
    - gsl 1.16
    - mpi4py
    - openblas
    - numpy x.x
    - scipy
    - python-dateutil
    - readline
    - poco
    - nexus
    - openssl
    - jsoncpp
    - tbb

  run:
    - python
    - cmake
    - pyyaml
    - boost 1.61.*
    - hdf4
    - hdf5 1.8.18
    - h5py
    - muparser
    - gsl 1.16
    - mpi4py
    - openblas
    - numpy x.x
    - scipy
    - python-dateutil
    - readline
    - poco
    - nexus
    - openssl
    - jsoncpp
    - tbb

build:
  script_env:
    - CC
    - CXX
    - OPENGL_gl_LIBRARY
    - OPENGL_glu_LIBRARY

about:
  home:
  license:
  license_file:
