{% set version = "5.0.20200903.1942" %}
{% set git_rev = "bc5e2fd0fb4da3a4f9b4d421c5b8f9140aa0fb88" %}

package:
  name: mantid-framework
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    - blas
    - boost
    - cmake
    - eigen
    - gsl
    - gxx_linux-64 7.3.* [linux64]
    - h5py
    - hdf4
    - hdf5
    - jsoncpp
    - librdkafka
    - muparser
    - nexus
    - ninja
    - numpy {{ numpy }}
    - openblas
    - openssl
    - pkg-config
    - poco
    - python {{ python }}
    - tbb-devel

  run:
    - boost
    - h5py
    - librdkafka
    - nexus
    - numpy
    - openblas
    - poco
    - python
    - python-dateutil
    - pyyaml
    - scipy
    - six
    - tbb

build:

about:
  home:
  license:
  license_file:
