{% set version = "3.11.20171218.2114" %}
{% set git_rev = "3ae821d4ae9bc8b89d99894b0375318f5bbd27de" %}

package:
  name: mantid-framework
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    - python
    - cmake
    - boost 1.61.*
    - hdf4
    - hdf5 1.8.18
    - h5py
    - muparser
    - gsl 1.16
    - mpi4py
    - openblas
    - numpy 1.13.3 py27_blas_openblas_201
    - scipy
    - python-dateutil
    - readline
    - poco
    - nexus
    - openssl
    - jsoncpp
    - tbb

  run:
    - python
    - cmake
    - pyyaml
    - boost 1.61.*
    - hdf4
    - hdf5 1.8.18
    - h5py
    - muparser
    - gsl 1.16
    - mpi4py
    - openblas
    - numpy 1.13.3 py27_blas_openblas_201
    - scipy
    - python-dateutil
    - readline
    - poco
    - nexus
    - openssl
    - jsoncpp
    - tbb

build:
  script_env:
    - CC
    - CXX
    - OPENGL_gl_LIBRARY
    - OPENGL_glu_LIBRARY
  string: py27_np113_openblas201

about:
  home:
  license:
  license_file:
