{% set version = "3.9.20170512.2148" %}
{% set git_rev = "be614658ea886bf7951a2f500ebba4cf51333097" %}

package:
  name: mantid-framework
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    - python
    - cmake
    - boost 1.61.*
    - hdf4
    - hdf5 1.8.*
    - h5py
    - muparser
    - gsl
    - mpi4py
    - openblas
    - numpy
    - scipy
    - dateutil
    - readline
    - poco
    - nexus
    - openssl
    - jsoncpp
    - tbb

  run:
    - python
    - cmake
    - boost 1.61.*
    - hdf4
    - hdf5 1.8.*
    - h5py
    - muparser
    - gsl
    - mpi4py
    - openblas
    - numpy
    - scipy
    - dateutil
    - readline
    - poco
    - nexus
    - openssl
    - jsoncpp
    - tbb

build:
  script_env:
    - CC
    - CXX
    - OPENGL_gl_LIBRARY
    - OPENGL_glu_LIBRARY

about:
  home:
  license:
  license_file:
