{% set version = "3.11.20180109.1450" %}
{% set git_rev = "7ce53f974851e0a7405d4b1d472f28473361bbd4" %}

package:
  name: mantid-framework
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    - python
    - cmake
    - boost 1.61.*
    - hdf4 4.2.13
    - hdf5 1.8.18
    - h5py
    - muparser 2.2.5
    - gsl 1.16
    - mpi4py
    - openblas 0.2.20
    - numpy 1.13.3 py27_blas_openblas_201
    - scipy
    - python-dateutil
    - readline
    - poco 1.7.3
    - nexus 4.3.1
    - openssl
    - jsoncpp 0.10.6
    - tbb 2018_20170919

  run:
    - python
    - cmake
    - pyyaml
    - boost 1.61.*
    - hdf4 4.2.13
    - hdf5 1.8.18
    - h5py
    - muparser 2.2.5
    - gsl 1.16
    - mpi4py
    - openblas 0.2.20
    - numpy 1.13.3 py27_blas_openblas_201
    - scipy
    - python-dateutil
    - readline
    - poco 1.7.3
    - nexus 4.3.1
    - openssl
    - jsoncpp 0.10.6
    - tbb 2018_20170919

build:
  script_env:
    - CC
    - CXX
    - OPENGL_gl_LIBRARY
    - OPENGL_glu_LIBRARY
  string: py27_np113_openblas201

about:
  home:
  license:
  license_file:
