{% set version = "3.9.20170323.1838" %}
{% set git_rev = "b05e24bbfbc96dc213a370f92ea581a777784732" %}

package:
  name: mantid-framework
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    - python
    - cmake
    - boost 1.61.*
    - hdf4
    - hdf5 1.8.15*
    - h5py
    - muparser
    - gsl
    - mpi4py
    - scipy
    - dateutil
    - readline
    - poco
    - nexus
    - openssl
    - jsoncpp
    - tbb

  run:
    - python
    - cmake
    - boost 1.61.*
    - hdf4
    - hdf5 1.8.15*
    - h5py
    - muparser
    - gsl
    - mpi4py
    - scipy
    - dateutil
    - readline
    - poco
    - nexus
    - openssl
    - jsoncpp
    - tbb

build:
  script_env:
    - CC
    - CXX
    - OPENGL_gl_LIBRARY
    - OPENGL_glu_LIBRARY

about:
  home:
  license:
  license_file:
