{% set version = "5.0.20200519.1419" %}
{% set git_rev = "bb3320265bfd15f6a9820816e12e5548d1127930" %}

package:
  name: mantid-framework
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    - blas
    - boost
    - cmake
    - eigen
    - gsl
    - gxx_linux-64 7.3.* [linux64]
    - h5py
    - hdf4
    - hdf5
    - jsoncpp
    - librdkafka
    - muparser
    - nexus
    - ninja
    - numpy {{ numpy }}
    - openblas
    - openssl
    - pkg-config
    - poco
    - python {{ python }}
    - tbb-devel

  run:
    - boost
    - h5py
    - librdkafka
    - nexus
    - numpy
    - openblas
    - poco
    - python
    - python-dateutil
    - pyyaml
    - scipy
    - six
    - tbb

build:

about:
  home:
  license:
  license_file:
