{% set version = "4.0.20190501.1216" %}
{% set git_rev = "2dce5b0c31140047afa2d3c3d603ff64ea68de8f" %}

package:
  name: mantid-framework
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - cmake
  host:
    - python
    - boost     {{ boost }}
    - eigen     {{ eigen }}
    - hdf4      {{ hdf4 }}
    - hdf5      {{ hdf5 }}
    - muparser  2.2.5 0
    - gsl       {{ gsl }}
    - openblas  {{ openblas }}
    - blas      {{ blas }}
    - numpy     {{ numpy }} 
    - poco      {{ poco }}
    - nexus     {{ nexus }}
    - jsoncpp   {{ jsoncpp }}
    - tbb       {{ tbb }}
    - librdkafka  {{ librdkafka }}
    - readline
    - openssl   {{ openssl }}
    - python-dateutil
    - h5py
    - mpi4py
    - scipy

  run:
    - python
    - boost
    - eigen
    - hdf4
    - hdf5
    - muparser 2.2.5 0
    - gsl
    - openblas
    - blas
    - numpy
    - poco
    - nexus
    - jsoncpp
    - tbb
    - librdkafka
    - readline
    - openssl
    - python-dateutil
    - h5py
    - mpi4py
    - scipy
    - scikit-image
    - pyyaml
    - pycifrw
    - matplotlib
    - six
    - cmake

build:
  script_env:
    - CC
    - CXX
    - OPENGL_gl_LIBRARY
    - OPENGL_glu_LIBRARY
    - OPENGL_INCLUDES
  string:

about:
  home:
  license:
  license_file:
