{% set version = "5.0.20200504.1630" %}
{% set git_rev = "07624deaeac25b1ffac109e0c8c587dc7683bdb9" %}

package:
  name: mantid-framework
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  host:
    - blas
    - boost
    - cmake
    - eigen
    - gsl
    - h5py
    - hdf4
    - hdf5
    - jsoncpp
    - librdkafka
    - muparser
    - nexus
    - ninja
    - numpy     {{ numpy }}
    - openblas
    - openssl
    - pkg-config
    - poco
    - python {{ python }}
    - qscintilla2
    - tbb-devel

  run:
    - boost
    - h5py
    - librdkafka
    - nexus
    - numpy
    - poco
    - python-dateutil
    - pyyaml
    - scipy
    - six
    - tbb

build:

about:
  home:
  license:
  license_file:
