{% set version = "3.12.20180409.1313" %}
{% set git_rev = "26a4efa4559ff2dc82b9c9574a1840968510c123" %}

package:
  name: mantid-framework
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    - python
    - cmake
    - boost     {{ boost }}
    - eigen     {{ eigen }}
    - hdf4      {{ hdf4 }}
    - hdf5      {{ hdf5 }}
    - h5py
    - muparser  {{ muparser }}
    - gsl       {{ gsl }}
    - mpi4py
    - openblas  {{ openblas }}
    - blas      {{ blas }}
    - numpy     {{ numpy }} 
    - scipy
    - python-dateutil
    - readline
    - poco      {{ poco }}
    - nexus     {{ nexus }}
    - openssl
    - jsoncpp   {{ jsoncpp }}
    - tbb       {{ tbb }}

  run:
    - python
    - cmake
    - pyyaml
    - boost
    - hdf4
    - hdf5
    - h5py
    - muparser
    - gsl
    - mpi4py
    - openblas
    - blas
    - numpy
    - scipy
    - matplotlib
    - python-dateutil
    - readline
    - poco
    - nexus
    - openssl
    - jsoncpp
    - tbb
    - pycifrw

build:
  script_env:
    - CC
    - CXX
    - OPENGL_gl_LIBRARY
    - OPENGL_glu_LIBRARY
  string:

about:
  home:
  license:
  license_file:
