{% set version = "3.8.20161121.1956" %}
{% set git_rev = "f2e3f8da4ac7e4823eae8740adda522b7ef76f02" %}

package:
  name: mantid-framework
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    - python
    - cmake
    - boost
    - hdf4
    - hdf5 1.8.15*
    - h5py
    - muparser
    - gsl
    - mpi4py
    - scipy
    - dateutil
    - readline
    - poco
    - nexus
    - openssl
    - jsoncpp
    - tbb

  run:
    - python
    - cmake
    - boost
    - hdf4
    - hdf5 1.8.15*
    - h5py
    - muparser
    - gsl
    - mpi4py
    - scipy
    - dateutil
    - readline
    - poco
    - nexus
    - openssl
    - jsoncpp
    - tbb

build:
  script_env:
    - OPENGL_gl_LIBRARY
    - OPENGL_glu_LIBRARY

about:
  home:
  license:
  license_file:
