package:
  name: jsoncpp
  version: "0.10.6"

source:
  git_rev: 0.10.6
  git_url: https://github.com/open-source-parsers/jsoncpp

requirements:
  build:
    - cmake
    - python

  run:
    - python

test:
  imports:
  

about:
  home: 
  license:
  license_file:
