package:
  name: poco
  version: "1.7.3"

source:
  git_rev: poco-1.7.3-release
  git_url: https://github.com/pocoproject/poco.git

requirements:
  build:
    - openssl
    - zlib

  run:
    - openssl
    - zlib

test:
  imports:
  

about:
  home: 
  license:
  license_file:
